### ISSUE TITLE
NBA api

### ISSUE THREAD

**Issue by anshulsoni4** [dishamodi0910/APIVerse#104]
### Brief Description 🤓

it has all data of the USA basketball league called NBA, from players to teams everything

### Provide reference!

https://rapidapi.com/api-sports/api/api-nba

### Select the open source program you are contributing to

hacktoberfest-23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @anshulsoni4🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
@anshulsoni4 Invalid issue syntax. Please refer to other issues in repository to see how to create a proper issue.

**Comment by dishamodi0910** [comment]
Hey @anshulsoni4 ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
