### ISSUE TITLE
Fixing typos across the Project

### ISSUE THREAD

**Issue by NIKHIL0VERMA** [dishamodi0910/APIVerse#106]
Hey @dishamodi0910,
I found some typos across multiple files. For example New_APIs/Recipe_Realm_API/rec.js line 28 Read Artcile

I would like to fix those under GSSOC'24. Kindly add the respective labels, level and assign this to me.

**Comment by dishamodi0910** [comment]
Greetings @NIKHIL0VERMA🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @NIKHIL0VERMA ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
