### ISSUE TITLE
[API Enhancement] : Enhacing the PokeAPI already present in Existing_API_Collection

### ISSUE THREAD

**Issue by its-kritika** [dishamodi0910/APIVerse#118]
### Brief Description 🤓

PokeAPI fetches details of any Pokemon that you love but it has no user interface. Being a user myself, I am not not able to easily search for the details of pokemon I like.  I will enhance the api by adding frontend, and fetching relevant data.

**Changes Suggestion:**
1. I will design the frontend of this api
2. A search feature will be introduced to help users easily find specific pokemon. This is especially useful as some pokemon currently appear at the top while others are only accessible by clicking "load more" which makes the search operation a tedious task.
![Screenshot (388)](https://github.com/dishamodi0910/APIVerse/assets/144522556/1a3f0a39-6ba4-405d-9497-00328e7fd2a1)
3. There are a lot of information fetched when searching for a specific pokemon, I will reduce that to fetch only relevant details.
![Screenshot (386)](https://github.com/dishamodi0910/APIVerse/assets/144522556/e9fb29af-d111-4821-b5e3-8626c7f2b029)
4. Add README.md file for the application

**How will I proceed?**
1. I will use Tailwind CSS to add enhancement styling.
2. Improve server side javascript files
3. Improve Client side javascript files
4. I will use NodeJS for backend ( only if necessary )

Kindly assign it to me.

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @its-kritika🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @its-kritika ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
