### ISSUE TITLE
[New API] : Hospital API

### ISSUE THREAD

**Issue by Varad0014** [dishamodi0910/APIVerse#120]
### Brief Description 🤓

An API for Hospital Management. The API will provide CRUD operations for-

- Patient Management
- Doctor Management
- Appointment Management along with Bills Management

### How will you develop it?🤩

I will use MongoDB as database and Node, Express and Mongoose in the backend. I will create appropriate routes and use controllers for the API. I will also use some seed data to populate the database. The seed file will also be included with other files.

### Deployment

None

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @Varad0014🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @Varad0014 ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
