### ISSUE TITLE
[New API] :  College Result Api

### ISSUE THREAD

**Issue by Yashgabani845** [dishamodi0910/APIVerse#128]
### Brief Description 🤓

so it is basically retiriving marks and grades 
there are 2 sides 
1. Students side who can read their marks,grads
2. Teacher who can upload ,update , delete marks ,grades and student as well
 whole crud operation could be performed on this api

### How will you develop it?🤩

i will implement this rest api with 2 sides and crud operation with endpoints ehich will perform crud,and restict to access of every operation according to role

### Deployment

No

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @Yashgabani845🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @Yashgabani845 ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
