### ISSUE TITLE
[New API] :  IP Address Information API

### ISSUE THREAD

**Issue by Helpinlakkad** [dishamodi0910/APIVerse#137]
### Brief Description 🤓

Through this API we can get information from the IP address. 
Information Like this :- 
city, region, country, loc, org, postal, Timezone etc...

### How will you develop it?🤩

1. Using Node and npm, install express, maxmind and axios.
2. download the GeoLite2 database.
3. using express make the API to get the data from the database.
4. return that data to the json format.

### Deployment

No

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @Helpinlakkad🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @Helpinlakkad ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
