### ISSUE TITLE
[New API] :  Quote API

### ISSUE THREAD

**Issue by Some1Uknow** [dishamodi0910/APIVerse#138]
### Brief Description 🤓

- Users can find quotes related to various genres like - happiness, motivation, life, peace, etc.

### How will you develop it?🤩

- Will use an expressjs server as backend
- Will keep all the quotes seperated by genre in a json file in the backend
- Will create routes for user to fetch quote based on the genre
- Server will be hosted on a service like Vercel, Render, etc.
- Will provide proper documentation on how to use the api

### Deployment

None

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @Some1Uknow🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @Some1Uknow ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
