### ISSUE TITLE
[New API] : Social Media API

### ISSUE THREAD

**Issue by Varad0014** [dishamodi0910/APIVerse#143]
### Brief Description 🤓

API provides some of the functionalities which are used in networking applications. It provides CRUD operations for - 

- User management
- Post content management
- Comments and likes management for Posts

Users can post text content. They have friends who can like or comment on posts.

### How will you develop it?🤩

I will use MongoDB as database and Node, Express and Mongoose in the backend. I will create appropriate routes and use controllers for the API. 

### Deployment

None

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @Varad0014🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @Varad0014 ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
