### ISSUE TITLE
[API Enhancement] : Bored API

### ISSUE THREAD

**Issue by Suyash878** [dishamodi0910/APIVerse#147]
## Current issue with Bored API:

The URL that this API currently uses to fetch the activities (ie: "https://www.boredapi.com/api/activity") is not live and is not giving the desired response.

![image](https://github.com/dishamodi0910/APIVerse/assets/141909257/397cad27-7d3a-41c2-b682-bf6a9d63161e)

## My solution:

I am planning on fixing this issue by making my own JSON file which will include all the activities one could do and host it somewhere publicly and use axios on that particular URL to fetch.  

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @Suyash878🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @Suyash878 ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
