### ISSUE TITLE
[New API] : Result marks Api

### ISSUE THREAD

**Issue by Yashgabani845** [dishamodi0910/APIVerse#160]
### Brief Description 🤓

As you closed my previous issue and told to add some more features like particular studnt marks,etc
so that you can give level 3 label 
in PR : #140 
and i can not work on closed issue so this issue is adding more advanced functionalities 

### How will you develop it?🤩

Reuslt Marks API
with 2roles
student role and treacher Role
Crud operation with marks and student as well.

### Deployment

None

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @Yashgabani845🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @Yashgabani845 ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
