### ISSUE TITLE
[Existing API Name] : JSON Placeholder API implementation

### ISSUE THREAD

**Issue by Yashgabani845** [dishamodi0910/APIVerse#163]
### Brief Description 🤓

this is very famous api which give large chunks of fake json data 
and i think this is very useful to most of the developers 
and anyone can use this implemenation easily in their projects

### Provide reference!

JSON PLACERHOLDER API

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by Yashgabani845** [comment]
gssoc24

**Comment by dishamodi0910** [comment]
Hey @Yashgabani845 ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
