### ISSUE TITLE
[Existing API Name] : combing both geolocation api and nominatim api 

### ISSUE THREAD

**Issue by Rohitha-pudu** [dishamodi0910/APIVerse#168]
### Brief Description 🤓

the Geolocation API to determine the user's current location accurately, With the help of the Nominatim API, the application identifies the user's location and retrieves detailed information such as the city, landmarks, and historical context associated with that location.

### Provide reference!

https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API
https://nominatim.org/

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @Rohitha-pudu🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @Rohitha-pudu ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️

**Comment by Rohitha-pudu** [comment]
> Hey @Rohitha-pudu ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗. In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). Thank you! ❣️ Happy Coding! ✨ Will See you soon❣️

may i know why it is closed> @dishamodi0910
