### ISSUE TITLE
[New API] : Book Management API

### ISSUE THREAD

**Issue by its-kritika** [dishamodi0910/APIVerse#179]
### Brief Description 🤓

A Book Management API is a web service that allows users to manage a collection of books. This type of API provides endpoints for performing CRUD (Create, Read, Update, Delete) operations on a database of books. 

Features:
- One can use this api to keep track of personal books they own in their shelf or library or book store.
- You can add, delete, update the book details.
- Authentication : For a more secure API,  authentication will be implemented  via JWT tokens.
- Error Handling: To manage scenarios like invalid inputs, non-existent book IDs, or database connection issues, error handling will be implemented.

### How will you develop it?🤩

I will built it using Node.js, Express and Postman

Endpoints:
- GET /users: Retrieve all users.
- GET /users/{id}: Retrieve user by ID.
- POST /users: Add a new user.
- PUT /users/{id}: Update a user by ID.
- DELETE /users/{id}: Delete a user by ID.
- GET /books: Retrieve all books.
- GET /books/{id}: Retrieve a specific book by ID.
- POST /books: Add a new book.
- PUT /books/{id}: Update a book by ID.
- DELETE /books/{id}: Delete a book by ID.

### Deployment

None

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @its-kritika🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @its-kritika ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
