### ISSUE TITLE
[New API] : Food Delivery Service API

### ISSUE THREAD

**Issue by Yashgabani845** [dishamodi0910/APIVerse#183]
### Brief Description 🤓

food service API! Build apps for recipes, meals, & restaurants. Access free, public data on ingredients, nutrition, menus.

it will have endpoints like:

1. Find recipes by ingredients: Enter your ingredients (like eggs, milk, flour) and get recipe ideas.
2. Search restaurants: Look for restaurants by type of food (Italian, Mexican) near you.
3. Food details: Look up a specific food (apple, chicken) to see its nutrients (vitamins, calories).
4. Create meal plans (advanced): Save your meals for the week (breakfast, lunch, dinner).

### How will you develop it?🤩

- i will use node-express for backend and mongodb database 
- and check all of the end points
- create all required models
- will make proper MVC model
- and make system smooth

### Deployment

No

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Hey @Yashgabani845 ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
