### ISSUE TITLE
[New API] : Open Library Book Search API

### ISSUE THREAD

**Issue by pankaj-bind** [dishamodi0910/APIVerse#192]
### Brief Description 🤓

The Open Library Book Search API is a web application that allows users to search for books by title, author, or subject. It retrieves book information, including titles, authors, and publication years, from the Open Library database.

Please assign me this under GSSoC'24

### How will you develop it?🤩

Frontend Interface (HTML): Provides the structure with a search form and a results section.

Styling (CSS): Ensures a clean, modern design for a better user experience.

Interaction Logic (JavaScript): Handles form submissions, fetches data from the Open Library API, and dynamically updates the results section with book details.

### Deployment

None

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @pankaj-bind🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @pankaj-bind ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
