### ISSUE TITLE
[Documentation Error] : A small typo in the README file.

### ISSUE THREAD

**Issue by MaryamMohamedYahya** [dishamodi0910/APIVerse#195]
### Brief Description 🤓

Under the heading "🚀When you can expect your PR will get accepted?"
Point 1: ✅ You should add either 1 new API or 1 existing APIafter testing the code properly. The file structure should be followed. README.md file should be present inside your folder.

There should be a space in the first point between the words API and testing

### Select the open source program you are contributing to

Other

### Code of Conduct

- [x] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @MaryamMohamedYahya🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @MaryamMohamedYahya ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
