### ISSUE TITLE
[Existing API Name] : PotterAPI

### ISSUE THREAD

**Issue by DonaldReddy** [dishamodi0910/APIVerse#198]
### Brief Description 🤓

PotterAPI is a Harry Potter API developed with Express.js and available in multiple languages.
This API stores information and images of books, characters, and spells. It provides a way to search for books, characters, and spells based on various criteria such as keywords, or id. The API returns detailed metadata and can include additional features such as image URLs for each character.

### Provide reference!

https://github.com/fedeperin/potterapi?tab=readme-ov-file

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @DonaldReddy🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @DonaldReddy ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
