### ISSUE TITLE
[API Enhancement] : COVID Tacker API

### ISSUE THREAD

**Issue by Vipullakum007** [dishamodi0910/APIVerse#201]
### Brief Description 🤓

it will fetch covid total cases , total deaths , total active cases , total recovery by using `disease.sh` api. 

### How develop it ?

Choose Data Source: Select a COVID-19 data API like disease.sh or a government health department's API.

Set Up Environment: Create a Node.js project and install necessary packages like Express.js and Axios.

Define Endpoints: Create endpoints for /countries, /countries/:countryCode, and /global to fetch COVID-19 data.

Fetch Data: Use Axios to make HTTP requests to the chosen API and format the data for each endpoint.

Handle Errors: Implement error handling for failed requests or invalid data.

Test: Test your API endpoints using tools like Postman to ensure they return the expected data.

Document: Create documentation explaining how to use each endpoint, expected responses, and error handling.

**_Screenshots_**
Default Page : 
![Screenshot 2024-06-02 101327](https://github.com/dishamodi0910/APIVerse/assets/127659443/5d6be01e-7f6e-4cf5-a215-b9c23b22ae7f)
Based on country : 
![Screenshot 2024-06-02 101400](https://github.com/dishamodi0910/APIVerse/assets/127659443/3afacf0e-2548-4e4a-9375-92c628c3a56d)
![Screenshot 2024-06-02 101443](https://github.com/dishamodi0910/APIVerse/assets/127659443/f326ca7b-b6d2-4729-8658-2f5ee4eb5b3c)

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @Vipullakum007🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @Vipullakum007 ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
