### ISSUE TITLE
[New API] : An API for encrypting and decrypting text message using the Pretty Good Privacy (PGP) algorithm.

### ISSUE THREAD

**Issue by SatwikMohan** [dishamodi0910/APIVerse#219]
### Brief Description 🤓

The API will consist of two end points one for encrypting and other for decrypting. The encryption and decryption will be done using the PGP algorithm. The API I created is in javascript using NodeJS. The algorithm is generally used in encrypting and decrypting emails for privacy.

### How will you develop it?🤩

I will develop the API by writing the program in Javascript in the NodeJS environment using the openpgp library. The API will have two endpoints representing their specific service of encryption or decryption post requests. In the data body there will be an input text. The response will contain the result of the algorithm.

### Deployment

None

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @SatwikMohan🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @SatwikMohan ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
