### ISSUE TITLE
[New API] : A-Z Medicine API for India

### ISSUE THREAD

**Issue by SatwikMohan** [dishamodi0910/APIVerse#228]
### Brief Description 🤓

The API would allow to browse through the medicine dataset of India and will allow to explore informations like name, price, manufacturer, composition and is it discontinued or not.

### How will you develop it?🤩

I will program the API using javascript under the NodeJS environment. The API will have a search by name, search by composition and search by manufacturers endpoints. It will also has an endpoint to return complete data for a medicine.

### Deployment

None

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @SatwikMohan🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @SatwikMohan ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
