### ISSUE TITLE
[Existing API Name] : FreeMealsdb api to get Food data

### ISSUE THREAD

**Issue by Sypher0Dronzer** [dishamodi0910/APIVerse#235]
### Brief Description 🤓

The FreeMealDB API is like a big library of recipes and food info that anyone can use. It helps people find out about different kinds of food, how to cook them, and what's in them. It's easy to use and great for anyone who loves food or wants to make cooking apps or websites.

### Provide reference!

https://www.themealdb.com/api.php/

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @Sypher0Dronzer🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @Sypher0Dronzer ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
