### ISSUE TITLE
[New API] : Add todo list API

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [dishamodi0910/APIVerse#247]
### Brief Description 🤓

I would like to add an API for a todo list application. These app provide a platform where users can list tasks, set deadlines, prioritize items, and track progress. 

### How will you develop it?🤩

In order to use app users need to have there own account. there will be features like sign in, sign up, view profile, change password, edit profile etc. JWT will be used for authentication.

Task will have properties including, id, name, description, deadline, category(Work, Personal, Health, Finance etc), priority (high, medium, low) and status(pending, in progress, completed)

Users can add, edit, delete, view, search, filter (by categories, status, and priority), sort by date.

Kindly please assign this issue to me under gssoc.

### Deployment

No

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @DharshiBalasubramaniyam🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️
