### ISSUE TITLE
[New API] :  Generate Joke Api

### ISSUE THREAD

**Issue by sivaprasath2004** [dishamodi0910/APIVerse#262]
### Brief Description 🤓

- I will Add for the new `Api` add in this project `Joke Api`
- please assign  me

### How will you develop it?🤩

![Screenshot from 2024-06-08 07-47-24](https://github.com/dishamodi0910/APIVerse/assets/121082414/d63b4178-b8c0-434a-a8c1-4f47e21eef66)

### Deployment

No

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @sivaprasath2004🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @sivaprasath2004 ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
