### ISSUE TITLE
[New API] :  Add Amine image generation API

### ISSUE THREAD

**Issue by ananyag309** [dishamodi0910/APIVerse#274]
### Brief Description 🤓

This anime image generation API provides users with a fun and creative way to generate custom anime-style images using web technologies.

Please assign it to me under gssoc

### How will you develop it?🤩

Develop an API using HTML, CSS, and JavaScript to dynamically generate anime-style images, incorporating randomness and user customization for character and background selection. Provide an intuitive web interface for users to interact with the API and generate images easily.

### Deployment

None

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @ananyag309🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by why-Radhika** [comment]
Hey @dishamodi0910, I noticed it has been some good amount of time since the issue was assigned abut no PR has been created so far. I would like to work on this issue. Could you please assign it to me?

**Comment by dishamodi0910** [comment]
Hey @ananyag309 ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
