### ISSUE TITLE
[Existing API Name] : Random Meme Generator Api 

### ISSUE THREAD

**Issue by komal-agarwal5** [dishamodi0910/APIVerse#284]
### Brief Description 🤓

I wish to add my deployed project on random meme generator api which will have the html,css and js files along with deployed link
This api generates random memes in a single click of a button
![337353279-e802d297-80d2-48fe-9f45-a0396219fb13](https://github.com/dishamodi0910/APIVerse/assets/122633300/33ad236c-e279-490b-abbd-33f19ab39ebd)

### Provide reference!

https://meme-api.com/gimme/wholesomememes

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @komal-agarwal5🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @komal-agarwal5 ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
