### ISSUE TITLE
[Existing API Name] : YouTube API Project: Video Search and Display

### ISSUE THREAD

**Issue by Praneeth-2602** [dishamodi0910/APIVerse#289]
### Brief Description 🤓

I will use the YouTube Data API to create a simple web application that allows users to search for YouTube videos and display the results. Users will be able to enter a search term, view a list of video results, and click on a video to watch it directly on the webpage.

### Provide reference!

https://developers.google.com/youtube/v3

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @Praneeth-2602🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @Praneeth-2602 ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
