### ISSUE TITLE
[Existing API Name] : Brewery API

### ISSUE THREAD

**Issue by atul2727** [dishamodi0910/APIVerse#299]
### Brief Description 🤓

This API enables users to:
- Fetch detailed information about breweries, including their name, type, city, state, country, phone, and website URL.
- Discover a random brewery every time the "Random Brewery" button is clicked.
- Provide a simple and easy-to-use interface for an intuitive user experience.
- Search for breweries by selecting a state from the dropdown list.

### Provide reference!

https://www.openbrewerydb.org/

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @atul2727🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @atul2727 ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
