### ISSUE TITLE
[Existing API Name] : Bhagavad Gita API

### ISSUE THREAD

**Issue by atul2727** [dishamodi0910/APIVerse#307]
### Brief Description 🤓

This API enables users to:

-> Fetch Verses: Retrieve detailed information about specific verses from the Bhagavad Gita, including the Sanskrit text and its English translation.
-> Discover a Random Verse: Discover a random verse every time the "Get Random Quote" button is clicked.
-> Simple and Easy-to-Use Interface.
-> Dropdown Selection: Select specific chapters and verses from dropdown lists to fetch quotes.

Endpoints:
/slok/{chapter}/{verse}/: Fetch a specific verse by chapter and verse number.
Example: https://bhagavadgitaapi.in/slok/2/47/

### Provide reference!

https://bhagavadgitaapi.in/

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @atul2727🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @atul2727 ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
