### ISSUE TITLE
[New API] : Implement Wikipedia API

### ISSUE THREAD

**Issue by thevijayshankersharma** [dishamodi0910/APIVerse#309]
### Brief Description 🤓

This issue aims to implement a Wikipedia API into our project. The API will fetch and display information about famous individuals based on user input.

### How will you develop it?🤩

We will develop this feature by:

Setting up an XMLHttpRequest in JavaScript to make requests to the Wikipedia API.
Dynamically updating the HTML content to display the retrieved information (title, thumbnail, description, extract).
Handling user input validation and ensuring appropriate error handling for API requests.
This integration will enhance our project by providing users with real-time access to Wikipedia's wealth of knowledge on public figures.

### Deployment

Yes

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @thevijayshankersharma🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @thevijayshankersharma ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
