### ISSUE TITLE
[Existing API Name] : Country Guide  API

### ISSUE THREAD

**Issue by kartikmehta18** [dishamodi0910/APIVerse#321]
### Brief Description 🤓

Create a country guide app that allows the user to search for a particular country and then displays information related to the searched country. I have use 'Rest Countries API

### Provide reference!

https://restcountries.com/

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @kartikmehta18🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by IshuSinghSE** [comment]
I wanted to express my interest in contributing to this project. As someone passionate about Python, JavaScript, and software development, I believe I can add value to the team.
/gssoc24

**Comment by kartikmehta18** [comment]
> Hey @kartikmehta18, The issue is already assigned and couldn't be assigned to you again.You can work on some other issue or create your own issue.🚀💗

ma'am issue is created by me I am waiting for you for assigning plz doo need full

**Comment by dishamodi0910** [comment]
Hey @kartikmehta18 ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
