### ISSUE TITLE
[New API] : Blog platform api

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [dishamodi0910/APIVerse#342]
### Brief Description 🤓

backend infrastructure for "Bloggie," a versatile blogging platform, using Node.js, Express.js, and MongoDB, facilitating seamless management of user and admin roles with role-based authentication.

robust user authentication functionalities, including sign-in and sign-up features, ensuring secure access for both users and administrators.

intuitive blogs management features, enabling users to create, edit, and delete blog posts, fostering dynamic content creation.

likes and comments management capabilities, enhancing user engagement and interaction within the platform.

tag-based search functionality, allowing users to easily discover relevant blogs by tags, optimizing content discovery and user experience.

tag management functionalities for administrators, enabling CRUD operations for tags, ensuring flexible and dynamic content categorization.

### How will you develop it?🤩

Using node.js, express.js and mongodb

### Deployment

None

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @DharshiBalasubramaniyam🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️
