### ISSUE TITLE
[New API] : Custom Captcha Generator API

### ISSUE THREAD

**Issue by PradnyaGaitonde** [dishamodi0910/APIVerse#347]
### Brief Description 🤓

A custom Captcha Generator is a security tool designed to create unique and unpredictable tests that differentiate between human users and automated bots. This generator leverages various challenge types, such as distorted text, image recognition, mathematical problems, and logic puzzles, to ensure robust protection against automated attacks. By implementing a diverse range of customizable Captcha challenges, it enhances the security of web applications, reduces the risk of spam and abuse, and improves user experience with intuitive and accessible verification methods.

### How will you develop it?🤩

The Custom Captcha Generator is a security tool designed to create unique and unpredictable tests to differentiate between human users and automated bots. This project will be developed using HTML, CSS, and JavaScript, ensuring a seamless integration into web applications with a focus on user-friendly design and robust functionality.

Please assign this to me under GSSOC24.

### Deployment

None

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @PradnyaGaitonde🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @PradnyaGaitonde ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
