### ISSUE TITLE
[New API] : Streamlabs API

### ISSUE THREAD

**Issue by revanth1718** [dishamodi0910/APIVerse#365]
### Brief Description 🤓

Offers free tools for integrating streaming features such as alerts and widgets. Great for enhancing your live streaming setup.

@dishamodi0910 assign me this issue

### How will you develop it?🤩

React

### Deployment

None

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @revanth1718🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by Hhujgin** [comment]
> ### Brief Description 🤓
> 
> Offers free tools for integrating streaming features such as alerts and widgets. Great for enhancing your live streaming setup.
> 
> 
> 
> @dishamodi0910 assign me this issue
> 
> ### How will you develop it?🤩
> 
> React
> 
> ### Deployment
> 
> None
> 
> ### Select the open source program you are contributing to
> 
> Other
> 
> ### Code of Conduct
> 
> - [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by revanth1718** [comment]
@Hhujgin, this issue is already assigned to me

**Comment by dishamodi0910** [comment]
Hey @revanth1718 ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
