### ISSUE TITLE
[New API] : Image_Compression_API

### ISSUE THREAD

**Issue by Helpinlakkad** [dishamodi0910/APIVerse#378]
### Brief Description 🤓

Through this API we can compress our image. This API supports the jpg/jpeg, png, svg file for compress.

### How will you develop it?🤩

1. Using node and npm install express, multer, compress-images, @squoosh/lib, gifsicle, svgo.
2. Here compress-images is the npm package with the help of this we can compress image.
3. using express make the post request of APIs and compression of the image.
4. show the compressed image in the compressed-images folder.
5. Here "@squoosh/lib" is only supported in the node version of ^12.0.0. or ^16.0.0. (so require to use node 16 is best for this).

### Deployment

No

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @Helpinlakkad🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @Helpinlakkad ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
