### ISSUE TITLE
[API Enhancement] :  Want to Add dark mode functionality

### ISSUE THREAD

**Issue by tusharyadav11** [dishamodi0910/APIVerse#61]
### Brief Description 🤓

 I would like to work on this functionality. in my earlier projects i have worked on this functionality. I would be grateful if you could assign me this functionality

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @tusharyadav11🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gdsc to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by tusharyadav11** [comment]
command/gdsc

**Comment by dishamodi0910** [comment]
Hey @tusharyadav11 ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️

**Comment by tusharyadav11** [comment]
@dishamodi0910 i want to work on this functionality
