### ISSUE TITLE
[New API] : NewsBuster 

### ISSUE THREAD

**Issue by shambhaveesrivastava12** [dishamodi0910/APIVerse#65]
### Brief Description 🤓

Aggregate news articles from various sources and categorize them based on topics like sports, technology, politics, etc. Users can search for news articles and filter them by date or source.

### How will you develop it?🤩

Reactjs

### Deployment

None

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @shambhaveesrivastava12🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gdsc to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by gungunjain36** [comment]
Hey!! I wanna work on this issue. Please assign this issue to me under GSSOC'24

**Comment by dishamodi0910** [comment]
Hey @gungunjain36, The issue is already assigned and couldn't be assigned to you again.You can work on some other issue or create your own issue.🚀💗

**Comment by dishamodi0910** [comment]
Hey @shambhaveesrivastava12 ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
