### ISSUE TITLE
[New API] : IIT ISM Subjects API

### ISSUE THREAD

**Issue by pspriyanshu601** [dishamodi0910/APIVerse#69]
### Brief Description 🤓

I will make a new APIs will be provide the information about all the subjects offered at IIT ISM.

### How will you develop it?🤩

I will crawl the website of IIT ISM to gather the data then will put this all into an api where you can get the lecture plan ,course instructor and all other stuff.

### Deployment

No

### Select the open source program you are contributing to

Other

### Code of Conduct

- [x] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @pspriyanshu601🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gdsc to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @pspriyanshu601, Don't forget to add README.md while pushing your changes!😄

**Comment by dishamodi0910** [comment]
Hey @pspriyanshu601 ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
