### ISSUE TITLE
[New API] : Adding Bored API

### ISSUE THREAD

**Issue by SougataXdev** [dishamodi0910/APIVerse#74]
### Brief Description 🤓

Bored API is a versatile tool designed to provide users with random activity suggestions when they're feeling bored. With this API, users can access a wide range of activities to spark inspiration and alleviate boredom. From creative hobbies to outdoor adventures, Bored API offers something for everyone.

### How will you develop it?🤩

Define the API endpoints: Determine the endpoints needed to access the random activity suggestions. For example:

/activity: Get a random activity suggestion.
Data Source: Identify a reliable source for activity suggestions. Bored API itself provides a comprehensive dataset of various activities.

Authentication: As Bored API is free to use, no authentication might be required for accessing the endpoints.

Data Formatting: Decide on the format in which the data will be returned. JSON is commonly used for its simplicity and ease of parsing.

Development Tools: Choose appropriate development tools and programming languages for building the API. Consider using open-source frameworks and libraries to streamline development.

Implementation:

Set up the project structure.
Define routes for the API endpoints.
Implement logic to fetch random activity suggestions.
Format the data as JSON responses.
Handle errors and edge cases gracefully.
Test the API thoroughly to ensure functionality.

### Deployment

Yes

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @SougataXdev🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by SougataXdev** [comment]
@dishamodi0910 assign this task to me

**Comment by dishamodi0910** [comment]
Hey @SougataXdev ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
