### ISSUE TITLE
[New API] : GeoPlaceAPI

### ISSUE THREAD

**Issue by Suyash878** [dishamodi0910/APIVerse#78]
## Overview
The Geocoding, Reverse Geocoding, and Place Autocomplete API provides developers with functionalities to convert addresses to geographic coordinates, find addresses from coordinates, and offer predictive search suggestions as users type.

## Development Approach
1. **Setup Express Server:** Create an Express.js server to handle HTTP requests.
2. **Integrate Google Maps API:** Utilize Axios to make HTTP requests to Google Maps API endpoints for geocoding, reverse geocoding, and place autocomplete.
3. **Define Endpoints:** Implement Express routes for geocoding, reverse geocoding, and autocomplete functionality.
4. **Handle Responses:** Parse and handle responses from OpenStreetMap Nominatim API, providing appropriate data back to the client.
5. **Error Handling:** Implement error handling for API requests and responses to ensure reliability.
6. **Testing:** Test the API endpoints thoroughly to ensure functionality and performance.

### Deployment

No

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @Suyash878🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @Suyash878 ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
