### ISSUE TITLE
[New API] : College Lectures API

### ISSUE THREAD

**Issue by Asymtode712** [dishamodi0910/APIVerse#79]
### Brief Description 🤓

This API serves as a basic system for managing college lectures. It allows users to perform CRUD (Create, Read, Update, Delete) operations on lecture resources. Each lecture resource has attributes such as title, instructor, time, and room.

### How will you develop it?🤩

- Setting Up Dependencies: The project utilizes Node.js and Express.js framework. We use body-parser middleware to parse incoming request bodies in JSON format.

- Defining Sample Data: We start by defining sample data for demonstration purposes. In a real-world scenario, this data would be stored in a database.

- Middleware Setup: We configure Express.js to use body-parser middleware to parse incoming JSON data.

- Routes: We define various routes for different CRUD operations on lectures:

       GET /lectures: Retrieves all lectures.
       GET /lectures/:id: Retrieves a specific lecture by its ID.
       POST /lectures: Creates a new lecture.
       PUT /lectures/:id: Updates an existing lecture.
       DELETE /lectures/:id: Deletes an existing lecture.

- Handlers for Routes:

       GET /lectures: Returns all lectures stored in memory.
       GET /lectures/:id: Retrieves a lecture with a specific ID.
       POST /lectures: Creates a new lecture based on the request body.
       PUT /lectures/:id: Updates the lecture with the specified ID based on the request body.
       DELETE /lectures/:id: Deletes the lecture with the specified ID.

- Error Handling: Proper error handling is implemented to handle cases where the requested resource is not found.

- Server Setup: We start the Express server and listen for incoming HTTP requests on a specified port.

### Deployment

No

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @Asymtode712🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @Asymtode712 ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
