### ISSUE TITLE
[New API] : Coding profile Details API

### ISSUE THREAD

**Issue by Kamaleshbala01** [dishamodi0910/APIVerse#84]
### Brief Description 🤓

Adding Details for the Coding platform like leetcode, codeChef and codeForces.

Profile Validation : check whether the username of the particular coding platform is vaild.
fetch Details : details like number of contest attend, number of problem solved, contest rating (current), global ranking and rating.

### How will you develop it?🤩

Backend : Node JS, Express JS.

### Deployment

None

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @Kamaleshbala01🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by Kamaleshbala01** [comment]
hi @dishamodi0910 I created PR for this New API.

assign me in this issue under GSSoc24.

**Comment by Kamaleshbala01** [comment]
hi @dishamodi0910  I'm still not assigned.

**Comment by dishamodi0910** [comment]
Contribution done. @Kamaleshbala01, closing the issue.

**Comment by dishamodi0910** [comment]
Hey @Kamaleshbala01 ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
