### ISSUE TITLE
[New API] : Galaxy API

### ISSUE THREAD

**Issue by Asymtode712** [dishamodi0910/APIVerse#85]
### Brief Description 🤓

The Galaxy Search API is a simple web service that allows users to search for information about galaxies. It provides endpoints for searching, creating, updating, and deleting galaxy records.

### How will you develop it?🤩

1. Setup:

- Installation: Install Node.js and required packages (Express.js, Body-parser, etc.).
- Project Structure: Organize files and directories for the API code.
- Sample Data: Define sample data for galaxies to use during development.

2. Implementation:

- Define Endpoints: Create routes for handling various CRUD operations on galaxies.
- Data Handling: Implement logic for handling data (e.g., fetching, creating, updating, deleting).
- Error Handling: Implement error handling to respond appropriately to client requests.
- Testing: Test each endpoint to ensure it works as expected using tools like Postman or cURL.

3. Frontend Integration:

- HTML & CSS: Create a simple HTML form for user input and apply CSS for styling.
- JavaScript: Write JavaScript code to handle user input, send requests to the API, and display results.

### Deployment

No

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @Asymtode712🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @Asymtode712 ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
