### ISSUE TITLE
[New API] : Random User API

### ISSUE THREAD

**Issue by sum1t-here** [dishamodi0910/APIVerse#90]
### Brief Description 🤓

The Random User API is a simple yet powerful tool for generating random user data for testing and development purposes. It allows developers to retrieve random user information such as names, email addresses, phone numbers, and profile pictures in various formats, including JSON, CSV, and YAML.

### How will you develop it?🤩

Will be using @faker-js/faker npm package for devloping the random user api

### Deployment

No

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @sum1t-here🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by amitkumar2308** [comment]
hey can you assign me this issue so i can contribute to your repositry

**Comment by dishamodi0910** [comment]
Hey @sum1t-here ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
