### ISSUE TITLE
[New API] : Attendance Portal API

### ISSUE THREAD

**Issue by Puskar-Roy** [dishamodi0910/APIVerse#94]
### 1. Authentication Routes
```bash
/api/auth/login                                POST               //for login
/api/auth/register                             POST               //for register
```

### 2. Users Routes

```bash
/api/users                                     GET               //for all users
/api/users/:id                                 GET               //for a single user
```

### 3. Attendance Routes

```bash
/api/attendance/counts/:userId                 GET               //for the number of attendance
/api/attendance/user/:attendenceId             GET               //for a single attendance
/api/attendance/date/:date                     GET               //for all the attendances of a date
/api/attendance/:userId                        GET               //for all the attendances of a user
/api/attendance/change-status/:attendanceId    PUT               //for change the status of an attendance
/api/attendance                                POST              //for create an attendance
/api/attendance/mark-absent                    POST              //for marking the absent users
/api/attendance/all                            POST              //for create all attendance
/api/attendance/:attendanceId                  DEL               //for delete an attendance
```

### Tech Stack

Node js, Express Js, Mongo DB, Mongoose, Typescript

### Deployment

Yes

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by dishamodi0910** [comment]
Greetings @Puskar-Roy🎀 ! , We are excited to have you dive into another issue with us!🚀
Your involvement in our project has been invaluable, and we're confident that your skills and insights will help us conquer this challenge😇. <h2> Use command /gssoc24 to self assign the issue. </h2> This issue represents an exciting opportunity for us to improve and enhance our project, and we are thrilled to have you on board.
 We request you to follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Looking for your PR soon! 
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).❣️

**Comment by dishamodi0910** [comment]
Hey @Puskar-Roy ! I wanted to inform you that we have closed issue.Thank you for your understanding, and we look forward to your continued engagement with our repository🤗.
 In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN). 
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️
